spring:
  application:
    name: time-manager

server:
  port: 8081
  servlet:
    context-path: /api  # This defines the base path for all endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: auth-server

keyStore:
  path: keystore.jks
  password: password
